"""add onboarding session tables

Revision ID: 87f6c8b969d3
Revises: 1c5b09407c12
Create Date: 2026-03-13 21:41:38.259389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87f6c8b969d3'
down_revision: Union[str, Sequence[str], None] = '1c5b09407c12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_sessions_id'), 'onboarding_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_onboarding_sessions_user_id'), 'onboarding_sessions', ['user_id'], unique=False)
    op.create_table('onboarding_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_key', sa.String(length=100), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['onboarding_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_answers_id'), 'onboarding_answers', ['id'], unique=False)
    op.create_index(op.f('ix_onboarding_answers_session_id'), 'onboarding_answers', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onboarding_answers_session_id'), table_name='onboarding_answers')
    op.drop_index(op.f('ix_onboarding_answers_id'), table_name='onboarding_answers')
    op.drop_table('onboarding_answers')
    op.drop_index(op.f('ix_onboarding_sessions_user_id'), table_name='onboarding_sessions')
    op.drop_index(op.f('ix_onboarding_sessions_id'), table_name='onboarding_sessions')
    op.drop_table('onboarding_sessions')
    # ### end Alembic commands ###
