"""add risk profile snapshots table

Revision ID: ad170d1912f9
Revises: 87f6c8b969d3
Create Date: 2026-03-17 23:12:48.308408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad170d1912f9'
down_revision: Union[str, Sequence[str], None] = '87f6c8b969d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_profile_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('profile_label', sa.String(length=50), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('dimension_scores', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['onboarding_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_profile_snapshots_id'), 'risk_profile_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_risk_profile_snapshots_session_id'), 'risk_profile_snapshots', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_profile_snapshots_session_id'), table_name='risk_profile_snapshots')
    op.drop_index(op.f('ix_risk_profile_snapshots_id'), table_name='risk_profile_snapshots')
    op.drop_table('risk_profile_snapshots')
    # ### end Alembic commands ###
