"""add portfolio scenario snapshots table

Revision ID: c01bfc99d8ab
Revises: ad170d1912f9
Create Date: 2026-03-18 02:09:46.864776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c01bfc99d8ab'
down_revision: Union[str, Sequence[str], None] = 'ad170d1912f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_scenario_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_type', sa.String(), nullable=False),
    sa.Column('total_budget', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('allocations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['onboarding_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_portfolio_scenario_snapshots_id'), 'portfolio_scenario_snapshots', ['id'], unique=False)
    op.drop_index(op.f('ix_risk_profile_snapshots_session_id'), table_name='risk_profile_snapshots')
    op.create_unique_constraint(None, 'risk_profile_snapshots', ['session_id'])
    op.drop_constraint(op.f('risk_profile_snapshots_session_id_fkey'), 'risk_profile_snapshots', type_='foreignkey')
    op.create_foreign_key(None, 'risk_profile_snapshots', 'onboarding_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'risk_profile_snapshots', type_='foreignkey')
    op.create_foreign_key(op.f('risk_profile_snapshots_session_id_fkey'), 'risk_profile_snapshots', 'onboarding_sessions', ['session_id'], ['id'])
    op.drop_constraint(None, 'risk_profile_snapshots', type_='unique')
    op.create_index(op.f('ix_risk_profile_snapshots_session_id'), 'risk_profile_snapshots', ['session_id'], unique=True)
    op.drop_index(op.f('ix_portfolio_scenario_snapshots_id'), table_name='portfolio_scenario_snapshots')
    op.drop_table('portfolio_scenario_snapshots')
    # ### end Alembic commands ###
